title: Gaurav Dixit
#logo: /
description: My Portfolio 
Aspiring Product Analyst with a background in Business Analytics, UX Analysis, and Data Science. Currently pursuing a Master of Science in Business Analytics at the University of California, Irvine. Passionate about leveraging data to drive business decisions and improve user experiences.  
#show_downloads:
theme: jekyll-theme-minimal
